### ISSUE TITLE
Admin endpoint: Please use symbols for polymorphic route arguments

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/api#102]
When I connect to /admin/ in production, I get this exception in the log:

```
I, [2022-02-07T21:44:05.324736 #20]  INFO -- : [c5ceec62-aa65-442a-ba34-cf22e7498400] Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.3ms | Allocations: 2597)
F, [2022-02-07T21:44:05.326237 #20] FATAL -- : [c5ceec62-aa65-442a-ba34-cf22e7498400]
[c5ceec62-aa65-442a-ba34-cf22e7498400] ActionView::Template::Error (Please use symbols for polymorphic route arguments.):
[c5ceec62-aa65-442a-ba34-cf22e7498400]     41:   <% end %>
[c5ceec62-aa65-442a-ba34-cf22e7498400]     42:
[c5ceec62-aa65-442a-ba34-cf22e7498400]     43:   <div>
[c5ceec62-aa65-442a-ba34-cf22e7498400]     44:     <%= link_to(
[c5ceec62-aa65-442a-ba34-cf22e7498400]     45:       t(
[c5ceec62-aa65-442a-ba34-cf22e7498400]     46:         "administrate.actions.new_resource",
[c5ceec62-aa65-442a-ba34-cf22e7498400]     47:         name: page.resource_name.titleize.downcase
[c5ceec62-aa65-442a-ba34-cf22e7498400]
[c5ceec62-aa65-442a-ba34-cf22e7498400] actionpack (6.0.4) lib/action_dispatch/routing/polymorphic_routes.rb:294:in `block in handle_list'
[c5ceec62-aa65-442a-ba34-cf22e7498400] actionpack (6.0.4) lib/action_dispatch/routing/polymorphic_routes.rb:289:in `map'
[c5ceec62-aa65-442a-ba34-cf22e7498400] actionpack (6.0.4) lib/action_dispatch/routing/polymorphic_routes.rb:289:in `handle_list'
[c5ceec62-aa65-442a-ba34-cf22e7498400] actionpack (6.0.4) lib/action_dispatch/routing/polymorphic_routes.rb:217:in `polymorphic_method'
[c5ceec62-aa65-442a-ba34-cf22e7498400] actionpack (6.0.4) lib/action_dispatch/routing/polymorphic_routes.rb:139:in `polymorphic_path'
[c5ceec62-aa65-442a-ba34-cf22e7498400] actionview (6.0.4) lib/action_view/routing_url_for.rb:102:in `url_for'
[c5ceec62-aa65-442a-ba34-cf22e7498400] actionview (6.0.4) lib/action_view/helpers/url_helper.rb:202:in `link_to'
[c5ceec62-aa65-442a-ba34-cf22e7498400] administrate (0.14.0) app/views/administrate/application/index.html.erb:44
...
```

**Comment by rnestler** [comment]
@dbrgn Is this still a problem? I could connect to https://watertemp-api.coredump.ch/admin/ without problems.

**Comment by dbrgn** [comment]
Yeah, seems to work! 🎉 

I had to figure out again how to authenticate... It's the public token as user and the private token as password 🙂
